web/config/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', views.index),
    path('select_type/', include('select_type.urls')),
    path('upload_image/', include('upload_image.urls')),
]

web/select_type/urls.py
from django.urls import path
from . import views


app_name = 'select_type'

urlpatterns = [
    path('', views.index, name='select_index'),
    path('result/shirts', views.post_shirts, name='post_shirts'),
    path('result/tshirts', views.post_tshirts, name='post_tshirts'),
    path('result/jeans', views.post_jeans, name='post_jeans'),
    path('test', views.get_ajax, name='ajax'),
]

web/upload_image/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'upload_image'

urlpatterns = [
    path('', views.index, name='upload_index'),
    path('result', views.post_clothes, name='post_clothes'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>Fashion Fruits</title>

    <meta name="description" content="" />
    <meta name="author" content="" />
    <link rel="icon" type="image/x-icon" href="assets/favicon.png" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    <link href="{% static 'css/main_styles.css' %}" rel="stylesheet" />

</head>
<body>
<!-- 네비게이션바 -->

{% include "navbar.html" %}


<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->

<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>
<script src="{% static 'js/main_scripts.js' %}"></script>
</body>
</html>

web/templates/footer.html
<!-- Footer-->
<footer class="footer text-center bg-dark">
    <div class="container px-4 px-lg-5 text-center text-white">
        <ul class="list-inline mb-5">
            <li class="list-inline-item">
                <a class="social-link rounded-circle text-dark mr-3" href="#!"><i class="icon-social-facebook"></i></a>
            </li>
            <li class="list-inline-item">
                <a class="social-link rounded-circle text-dark mr-3" href="#!"><i class="icon-social-twitter"></i></a>
            </li>
            <li class="list-inline-item">
                <a class="social-link rounded-circle text-dark" href="https://github.com/Duksung-AI-Lab/clothes"><i class="icon-social-github"></i></a>
            </li>
        </ul>
        <p class="text-muted small mb-0">Copyright &copy; Your Website 2022</p>
    </div>
</footer>

web/templates/index.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>DIY Fashion Search Engine</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Simple line icons-->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.5.5/css/simple-line-icons.min.css" rel="stylesheet" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/main_styles.css' %}" rel="stylesheet" />
    </head>
    <body id="page-top">
    {% block content %}

        <!-- Header-->
        <header class="masthead d-flex align-items-stat">
            <div class="container px-4 px-lg-5 text-center">
                <h1 class="mb-1">DIY Fashion Search</h1>
                <h3 class="mb-5"><em>Search Fashion Yourself With Your Imagination</em></h3>
{#                <a class="btn btn-dark btn-xl" href="#about">Find Out More</a>#}
            </div>
        </header>


{#        <!-- About-->#}
{#        <section class="about content-section bg-light" id="about">#}
{#            <div class="container px-4 px-lg-5 text-center">#}
{#                <div class="row gx-4 gx-lg-5 justify-content-center">#}
{#                    <div class="col-lg-10">#}
{#                        <h2>Fashion Fruit의 새로운 패션 검색 엔진을 만나보세요!</h2>#}
{#                        <p class="lead mb-5">#}
{#                            DIY Fashion Search Engine은 기존의 불편한 이미지 검색을 벗어나 여러분의 입맛에 맞는 소비를 도웁니다#}
{#<!--                            <a href="https://unsplash.com/">Unsplash</a>-->#}
{#                        </p>#}
{#                        <a class="btn btn-dark btn-xl" href="#services">What We Offer</a>#}
{#                    </div>#}
{#                </div>#}
{#            </div>#}
{#        </section>#}



{#        <!-- Services-->#}
{#        <section class="content-section bg-primary text-white text-center" id="services">#}
{#            <div class="container px-4 px-lg-5">#}
{#                <div class="content-section-heading">#}
{#<!--                    <h3 class="text-secondary mb-0">Services</h3>-->#}
{#                    <h2 class="mb-5">What We Offer</h2>#}
{#                </div>#}
{#                <div class="row gx-4 gx-lg-5">#}
{#                    <div class="col-lg-3 col-md-6 mb-5 mb-lg-0">#}
{#                        <span class="service-icon rounded-circle mx-auto mb-3"><i class="icon-screen-smartphone"></i></span>#}
{#                       <h4><strong>패션 이미지 검색</strong></h4>#}
{#                        <p class="text-faded mb-0">셔츠·티셔츠·청바지 패션 데이터 검색 </p>#}
{#                    </div>#}
{#                    <div class="col-lg-3 col-md-6 mb-5 mb-lg-0">#}
{#                        <span class="service-icon rounded-circle mx-auto mb-3"><i class="icon-pencil"></i></span>#}
{#                        <h4><strong>높은 정확도</strong></h4>#}
{#                        <p class="text-faded mb-0">딥러닝 분류 모델 기반의 검색 시스템</p>#}
{#                    </div>#}
{#                    <div class="col-lg-3 col-md-6 mb-5 mb-md-0">#}
{#                        <span class="service-icon rounded-circle mx-auto mb-3"><i class="icon-like"></i></span>#}
{#                        <h4><strong>원하는 패션 이미지 생성</strong></h4>#}
{#                        <p class="text-faded mb-0">#}
{#                            딥러닝 생성 모델의 패션 이미지#}
{#<!--                            <i class="fas fa-heart"></i>-->#}
{#                        </p>#}
{#                    </div>#}
{#                    <div class="col-lg-3 col-md-6">#}
{#                        <span class="service-icon rounded-circle mx-auto mb-3"><i class="icon-mustache"></i></span>#}
{#                        <h4><strong>이미지 검색 기능</strong></h4>#}
{#                        <p class="text-faded mb-0">자신의 패션 이미지로 검색 가능</p>#}
{#                    </div>#}
{#                </div>#}
{#            </div>#}
{#        </section>#}

        <!-- Callout-->
{#        <section class="callout">#}
{#            <div class="container px-4 px-lg-5 text-center">#}
{#                <h2 class="mx-auto mb-5">#}
{#                    DIY <em>Fashion Search</em>#}
{#                    시작하기#}
{#                </h2>#}
{#                <a class="btn btn-dark btn-lg" href="{% url 'select_type:select_index' %}">Select Type</a>#}
{#                <a class="btn btn-dark btn-lg" href="{% url 'upload_image:upload_index' %}">Upload Image</a>#}
{#            </div>#}
{#        </section>#}



        <!-- Portfolio-->
{#        <section class="content-section" id="portfolio">#}
{#            <div class="container px-4 px-lg-5">#}
{#                <div class="content-section-heading text-center">#}
{#<!--                    <h3 class="text-secondary mb-0">Portfolio</h3>-->#}
{#                    <h2 class="mb-5"><strong>We Are Fashion Fruits</strong></h2>#}
{#                </div>#}
{#                <div class="row gx-0">#}
{#                    <div class="col-lg-6">#}
{#                        <a class="portfolio-item" href="#!">#}
{#                            <div class="caption">#}
{#                                <div class="caption-content">#}
{#                                    <div class="h3">김규리</div>#}
{#                                    <p class="mb-0">덕성여자대학교 IT미디어공학과</p>#}
{#                                    <p class="mb-0">멋쟁2</p>#}
{#                                </div>#}
{#                            </div>#}
{#                            <img class="img-fluid" src="{% static 'assets/img/bg4.jpg' %}" alt="..." />#}
{#                        </a>#}
{#                    </div>#}
{#                    <div class="col-lg-6">#}
{#                        <a class="portfolio-item" href="#!">#}
{#                            <div class="caption">#}
{#                                <div class="caption-content">#}
{#                                    <div class="h3">이하영</div>#}
{#                                    <p class="mb-0">덕성여자대학교 IT미디어공학과</p>#}
{#                                    <p class="mb-0">므쨍이</p>#}
{#                                </div>#}
{#                            </div>#}
{#                            <img class="img-fluid" style="opacity: 80%;" src="{% static 'assets/img/fashion4.jpg' %}" alt="..." />#}
{#                        </a>#}
{#                    </div>#}
{#                    <div class="col-lg-6">#}
{#                        <a class="portfolio-item"  href="#!">#}
{#                            <div class="caption">#}
{#                                <div class="caption-content">#}
{#                                    <div class="h3">장혜림</div>#}
{#                                    <p class="mb-0">덕성여자대학교 IT미디어공학과</p>#}
{#                                    <p class="mb-0">멋쩅이</p>#}
{#                                </div>#}
{#                            </div>#}
{#                            <img class="img-fluid" style="opacity: 80%" src="{% static 'assets/img/fashion7.jpg' %}" alt="..." />#}
{#                        </a>#}
{#                    </div>#}
{#                    <div class="col-lg-6">#}
{#                        <a class="portfolio-item" href="#!">#}
{#                            <div class="caption">#}
{#                                <div class="caption-content">#}
{#                                    <div class="h3">이현지</div>#}
{#                                    <p class="mb-0">덕성여자대학교 IT미디어공학과</p>#}
{#                                    <p class="mb-0">개백수</p>#}
{#                                </div>#}
{#                            </div>#}
{#                            <img class="img-fluid" style="opacity: 80%" src="{% static 'assets/img/bg3.jpg' %}" alt="..." />#}
{#                        </a>#}
{#                    </div>#}
{#                </div>#}
{#            </div>#}
{#        </section>#}


<!--        &lt;!&ndash; Call to Action&ndash;&gt;-->
<!--        <section class="content-section bg-primary text-white">-->
<!--            <div class="container px-4 px-lg-5 text-center">-->
<!--                <h2 class="mb-4">The buttons below are impossible to resist...</h2>-->
<!--                <a class="btn btn-xl btn-light me-4" href="#!">Click Me!</a>-->
<!--                <a class="btn btn-xl btn-dark" href="#!">Look at Me!</a>-->
<!--            </div>-->
<!--        </section>-->
        <!-- Map-->

{#        <div class="content-section-heading text-center">#}
{#            <h2 class="mb-5">#}
{#                <strong>#}
{#                Directions#}
{#                </strong>#}
{#            </h2>#}
{#        </div>#}
{##}
{#        <div class="map" id="contact">#}
{#            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1579.4462309715168!2d127.01653935640721!3d37.6517321886627!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x357cbd6c9792ba67%3A0x6998ded8137103f6!2z642V7ISx7Jes7J6Q64yA7ZWZ6rWQIOygleuztOuvuOuUlOyWtOuMgO2VmQ!5e0!3m2!1sko!2skr!4v1663037120938!5m2!1sko!2skr" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>#}
{#            <br />#}
{#            <small><a href="https://maps.google.com/maps?f=q&amp;source=embed&amp;hl=en&amp;geocode=&amp;q=Twitter,+Inc.,+Market+Street,+San+Francisco,+CA&amp;aq=0&amp;oq=twitter&amp;sll=28.659344,-81.187888&amp;sspn=0.128789,0.264187&amp;ie=UTF8&amp;hq=Twitter,+Inc.,+Market+Street,+San+Francisco,+CA&amp;t=m&amp;z=15&amp;iwloc=A"></a></small>#}
{#        </div>#}

<a class="scroll-to-top rounded btn btn-dark" href="#mainNav"><i class="fas fa-angle-up"></i></a>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/main_scripts.js' %}"></script>
{% endblock %}
    </body>
</html>

web/templates/index_old.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Scrolling Nav - Start Bootstrap Template</title>
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
</head>
<body id="page-top">
{% block content %}
    <!-- Header-->
    <header class="bg-primary bg-gradient text-white">
        <div class="container px-4 text-center">
            <h1 class="fw-bolder">Welcome to Scrolling Navi</h1>
            <p class="lead">A functional Bootstrap 5 boilerplate for one page scrolling websites</p>
            <a class="btn btn-lg btn-light" href="#about">Start scrolling!</a>
        </div>
    </header>
    <!-- About section-->
    <section id="about">
        <div class="container px-4">
            <div class="row gx-4 justify-content-center">
                <div class="col-lg-8">
                    <h2>About this page</h2>
                    <p class="lead">This is a great place to talk about your webpage. This template is purposefully unstyled so you can use it as a boilerplate or starting point for you own landing page designs! This template features:</p>
                    <ul>
                        <li>Clickable nav links that smooth scroll to page sections</li>
                        <li>Responsive behavior when clicking nav links perfect for a one page website</li>
                        <li>Bootstrap's scrollspy feature which highlights which section of the page you're on in the navbar</li>
                        <li>Minimal custom CSS so you are free to explore your own unique design options</li>
                    </ul>
                </div>
            </div>
        </div>
    </section>
    <!-- Services section-->
    <section class="bg-light" id="services">
        <div class="container px-4">
            <div class="row gx-4 justify-content-center">
                <div class="col-lg-8">
                    <h2>Services we offer</h2>
                    <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut optio velit inventore, expedita quo laboriosam possimus ea consequatur vitae, doloribus consequuntur ex. Nemo assumenda laborum vel, labore ut velit dignissimos.</p>
                </div>
            </div>
        </div>
    </section>
    <!-- Contact section-->
    <section id="contact">
        <div class="container px-4">
            <div class="row gx-4 justify-content-center">
                <div class="col-lg-8">
                    <h2>Contact us</h2>
                    <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vero odio fugiat voluptatem dolor, provident officiis, id iusto! Obcaecati incidunt, qui nihil beatae magnam et repudiandae ipsa exercitationem, in, quo totam.</p>
                </div>
            </div>
        </div>
    </section>
    <!-- Footer-->
    <footer class="py-5 bg-dark">
        <div class="container px-4"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2022</p></div>
    </footer>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="{% static 'js/scripts.js' %}"></script>
{% endblock %}
</body>
</html>

web/templates/navbar.html
{% load static %}
<!-- 네비게이션바 -->
<!-- Navigation-->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark" id="mainNav">
    <div class="container px-4">
{#        <a href="/" class="navbar-left"><img src="{% static 'assets/img/logo.png' %}" style="width: 50px; padding-right: 10px;"></a>#}
{#        <a class="navbar-brand" href="/">Fashion Fruits</a>#}
        <a class="navbar-brand" href="/">DIY Fashion Search</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item"><a class="nav-link" href="{% url 'select_type:select_index' %}">Select Type</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'upload_image:upload_index' %}">Upload Image</a></li>
                <li class="nav-item"><a class="nav-link" href="https://github.com/Duksung-AI-Lab/clothes">GitHub</a></li>
                <li class="nav-item"><a class="nav-link" href="https://sites.google.com/view/dswuaiotlab">Duksung AIoT Lab</a></li>
            </ul>
        </div>
    </div>
</nav>

web/templates/result.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Result</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles_result.css' %}" rel="stylesheet" />
    </head>

    <body>
    {% block content %}
        <!-- Header-->
        <header class="bg-dark py-5">
            <div class="container px-4 px-lg-5 my-5">
                <div class="text-center text-white">
                    <h1 class="display-4 fw-bolder">Shop in style</h1>
                    <p class="lead fw-normal text-white-50 mb-0">With this shop hompeage template</p>
                </div>
            </div>
        </header>

        <!-- Section -->
        <section class="py-5">

            <div class="container px-4 px-lg-5 mt-5">
            {% if shirts %}
                <h2>{{ shirts|length }} 개의 결과</h2>
                {% if filter %}
                    <h5>
                    {% for item in filter %}
                    <span class="badge bg-info text-dark">{{ item }}</span>
                    {% endfor %}
                    </h5>
                {% endif %}<br>
                <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4">

                    {% for shirt in shirts %}
                    <div class="col mb-5">
                        <div class="card h-100">
                            <!-- Product image-->
                            <img class="card-img-top" src="{% get_static_prefix %}images/result_img/Shirts/{{ shirt.filename }}" alt="{{ shirt.filename }}" />
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->

                                    <h5 class="fw-bolder">{{ shirt.name }}</h5>
                                    <!-- Product price-->
                                    {{ shirt.price }}
                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{{ shirt.link }}">Go to shop</a></div>
                            </div>
                        </div>
                    </div>
                    {%  endfor %}
                </div>

            {% elif tshirts %}
                <h3>{{ tshirts|length }} 개의 결과</h3>
                {% if filter %}
                    <h5>
                    {% for item in filter %}
                    <span class="badge bg-info text-dark">{{ item }}</span>
                    {% endfor %}
                    </h5>
                {% endif %}<br>
                <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4">

                    {% for tshirt in tshirts %}

                    <div class="col mb-5">
                        <div class="card h-100">
                            <!-- Product image-->
                            <img class="card-img-top" src="{% get_static_prefix %}images/result_img/Tshirts/{{ tshirt.filename }}" alt="{{ tshirt.filename }}" />
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">{{ tshirt.name }}</h5>
                                    <!-- Product price-->
                                    {{ tshirt.price }}
                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{{ tshirt.link }}">Go to shop</a></div>
                            </div>
                        </div>
                    </div>
                    {%  endfor %}
                </div>

            {% elif jeans %}
                <h3>{{ jeans|length }} 개의 결과</h3>
                <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4">

                    {% for jean in jeans %}
                    <div class="col mb-5">
                        <div class="card h-100">
                            <!-- Product image-->
                            <img class="card-img-top" src="{% get_static_prefix %}images/result_img/Jeans/{{ jean.filename }}" alt="{{ jean.filename }}" />
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->

                                    <h5 class="fw-bolder">{{ jean.name }}</h5>
                                    <!-- Product price-->
                                    {{ jean.price }}
                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{{ jean.link }}">Go to shop</a></div>
                            </div>
                        </div>
                    </div>
                    {%  endfor %}
                </div>

            {% else %}
                <h4>There are no matching data found in the database.</h4>
                <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
            {% endif %}

            </div>
        </section>
        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2022</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts_result.js' %}"></script>
    {% endblock %}
    </body>

</html>